<a href="https://colab.research.google.com/github/sai14karthik/Soft-Computing-/blob/main/AP211100310_SC_LAB4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


# N. Sai KARTHIK AP21110010310 CSE-E
## Adaline

In [3]:
def Adaline(Input, Target, lr=0.2, stop=0.001):
    weight = np.random.random(Input.shape[1])
    bias   = np.random.random(1)

    Error=[stop +1]
    while Error[-1] > stop or Error[-1]-Error[-2] > 0.0001:
        error = []
        for i in range(Input.shape[0]):
            Y_input = sum(weight*Input[i]) + bias

            for j in range(Input.shape[1]):
                weight[j]=weight[j] + lr*(Target[i]-Y_input)*Input[i][j]

            bias=bias + lr*(Target[i]-Y_input)

            error.append((Target[i]-Y_input)**2)
        Error.append(sum(error))
        print('Error :',Error[-1])
    return weight, bias

In [4]:
x = np.array([
    [45, 50, 60],  # Pass
    [30, 35, 25],  # Fail
    [80, 70, 90],  # Pass
    [20, 25, 15],  # Fail
])
t =  np.array([1, 0, 1, 0])

In [5]:
w,b = Adaline(x, t, lr=0.2, stop=0.001)
print('weight :',w)
print('Bias :',b)

Error : [4.11147985]
Error : [0.77596235]
Error : [0.49462744]
Error : [0.34072286]
Error : [0.23574635]
Error : [0.1631547]
Error : [0.11291734]
Error : [0.07814875]
Error : [0.05408582]
Error : [0.03743216]
Error : [0.02590635]
Error : [0.01792948]
Error : [0.01240878]
Error : [0.00858797]
Error : [0.00594363]
Error : [0.00411352]
Error : [0.00284692]
Error : [0.00197032]
Error : [0.00136363]
Error : [0.00094375]
weight : [0.01063644 0.01063644 0.98697307]
Bias : [0.01063644]


<ipython-input-3-e54b0ff43270>:12: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  weight[j]=weight[j] + lr*(Target[i]-Y_input)*Input[i][j]


In [6]:
def prediction(X,w,b):
	y=[]
	for i in range(X.shape[0]):
		x = X[i]
		y.append(sum(w*x)+b)
	return y
prediction(x,w,b)


[array([1.0188824]),
 array([0.99760951]),
 array([0.99760951]),
 array([-0.99760951])]