<a href="https://colab.research.google.com/github/sai14karthik/Soft-Computing-/blob/main/AP211100310_SC_LAB3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# N. Sai KARTHIK AP21110010310 CSE-E
## Adaline


In [ ]:
import numpy as np


In [ ]:
def Adaline(Input, Target, lr=0.2, stop=0.001):
    weight = np.random.random(Input.shape[1])
    bias   = np.random.random(1)

    Error=[stop +1]
    while Error[-1] > stop or Error[-1]-Error[-2] > 0.0001:
        error = []
        for i in range(Input.shape[0]):
            Y_input = sum(weight*Input[i]) + bias

            for j in range(Input.shape[1]):
                weight[j]=weight[j] + lr*(Target[i]-Y_input)*Input[i][j]

            bias=bias + lr*(Target[i]-Y_input)

            error.append((Target[i]-Y_input)**2)
        Error.append(sum(error))
        print('Error :',Error[-1])
    return weight, bias

In [ ]:
x = np.array([[1.0, 1.0, 1.0],
              [1.0, -1.0, 1.0],
              [-1.0, 1.0, 1.0],
              [-1.0, -1.0, -1.0]])
t = np.array([1, 1, 1, -1])

In [ ]:
w,b = Adaline(x, t, lr=0.2, stop=0.001)
print('weight :',w)
print('Bias :',b)

Error : [1.84000612]
Error : [1.0972663]
Error : [0.77348797]
Error : [0.53593403]
Error : [0.3709382]
Error : [0.25672292]
Error : [0.17767493]
Error : [0.12296672]
Error : [0.08510381]
Error : [0.05889934]
Error : [0.04076353]
Error : [0.02821196]
Error : [0.01952516]
Error : [0.01351313]
Error : [0.00935228]
Error : [0.0064726]
Error : [0.00447961]
Error : [0.00310029]
Error : [0.00214567]
Error : [0.00148499]
Error : [0.00102775]
Error : [0.00071129]
weight : [0.00923402 0.00923402 0.98869069]
Bias : [0.00923402]


<ipython-input-7-e54b0ff43270>:12: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  weight[j]=weight[j] + lr*(Target[i]-Y_input)*Input[i][j]


In [ ]:
def prediction(X,w,b):
	y=[]
	for i in range(X.shape[0]):
		x = X[i]
		y.append(sum(w*x)+b)
	return y
prediction(x,w,b)


[array([1.01639273]),
 array([0.9979247]),
 array([0.9979247]),
 array([-0.9979247])]